"""The app icon, "comes true": readings easing in along the dial's arc, warming from amber to
sage, arriving at centre in the lock bloom. One set of geometry writes every form of it:

- the adaptive launcher icon's background, foreground and monochrome (themed) layers, as vectors
- tuner_mark, the visible middle of the icon as one vector, for the permission screen
- the 512 px Play store icon, rendered here

Geometry is in adaptive-icon units: a 108 canvas whose middle 72 is visible and whose inner
66-unit circle survives every launcher's mask.

    python icon.py
"""
import math
import os

from PIL import Image, ImageDraw, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
RES = os.path.join(ROOT, "app", "src", "main", "res")
STORE_ICON = os.path.join(ROOT, "fastlane", "metadata", "android", "en-US", "images", "icon.png")

# The app's dusk palette (ui/theme/Color.kt).
BG = (22, 32, 29)        # background
GLOW = (37, 55, 49)      # backgroundGlow
MUTED = (167, 182, 174)  # inkMuted
SAGE = (156, 197, 176)   # inTune
HALO = (212, 237, 223)   # glow
AMBER = (227, 166, 91)   # drift

# The dial: an arc centred below the mark, so its top sits just above the icon's middle.
CX, CY, R, SPAN = 54.0, 89.0, 38.0, 50.0
ARC_WIDTH = 1.8
TICK = (R + 5.5, R + 12.0, 2.2)                   # inner and outer radius, width
TRAIL = [-42.0, -29.5, -19.5, -12.0, -6.8]        # degrees from top: each reading closer
ARRIVAL = 4.6                                     # radius of the dot at centre
BLOOM = 20.0                                      # radius of its soft halo
LIFT_CENTER, LIFT_RADIUS, LIFT = (54.0, 50.0), 46.0, 0.55


def lerp(a, b, t):
    return tuple(round(a[i] + (b[i] - a[i]) * t) for i in range(3))


def smooth(t):
    return t * t * (3 - 2 * t)


def on_arc(deg, r=R):
    a = math.radians(deg)
    return CX + r * math.sin(a), CY - r * math.cos(a)


def trail():
    """(x, y, radius, colour, monochrome alpha) for each reading on the way in."""
    out = []
    for i, deg in enumerate(TRAIL):
        t = i / (len(TRAIL) - 1)
        x, y = on_arc(deg)
        colour = lerp(BG, lerp(AMBER, SAGE, smooth(t)), 0.35 + 0.6 * t)
        out.append((x, y, 1.7 + 1.3 * t, colour, 0.4 + 0.6 * t))
    return out


ARC_COLOUR = lerp(BG, MUTED, 0.45)
LIFT_COLOUR = lerp(BG, GLOW, LIFT)


# region Vectors

def hexa(rgb, alpha=1.0):
    return "#%02X%02X%02X%02X" % (round(alpha * 255), *rgb)


def circle(x, y, r):
    return f"M{x - r:.2f},{y:.2f}a{r:.2f},{r:.2f} 0 1,0 {2 * r:.2f},0a{r:.2f},{r:.2f} 0 1,0 {-2 * r:.2f},0z"


def arc_path():
    x0, y0 = on_arc(-SPAN)
    x1, y1 = on_arc(SPAN)
    return f"M{x0:.2f},{y0:.2f}A{R:.2f},{R:.2f} 0 0,1 {x1:.2f},{y1:.2f}"


def tick_path():
    x0, y0 = on_arc(0, TICK[0])
    x1, y1 = on_arc(0, TICK[1])
    return f"M{x0:.2f},{y0:.2f}L{x1:.2f},{y1:.2f}"


def vector(body, size=108, viewport=108, offset=0.0):
    group = f'    <group android:translateX="{-offset}" android:translateY="{-offset}">\n{body}    </group>\n' if offset else body
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by fastlane/capture/icon.py; edit the geometry there. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    xmlns:aapt="http://schemas.android.com/aapt"\n'
        f'    android:width="{size}dp"\n    android:height="{size}dp"\n'
        f'    android:viewportWidth="{viewport}"\n    android:viewportHeight="{viewport}">\n'
        f"{group}</vector>\n"
    )


def background_body():
    cx, cy = LIFT_CENTER
    stops = "".join(
        f'                    <item android:offset="{d}" android:color="{hexa(lerp(LIFT_COLOUR, BG, smooth(d)))}" />\n'
        for d in (0.0, 0.25, 0.5, 0.75, 1.0)
    )
    return (
        '    <path android:pathData="M0,0h108v108h-108z">\n'
        '        <aapt:attr name="android:fillColor">\n'
        f'            <gradient android:type="radial" android:centerX="{cx}" android:centerY="{cy}" android:gradientRadius="{LIFT_RADIUS}">\n'
        f"{stops}"
        "            </gradient>\n"
        "        </aapt:attr>\n"
        "    </path>\n"
    )


def foreground_body(mono=False):
    white = (255, 255, 255)
    body = []
    body.append(
        f'    <path android:pathData="{arc_path()}" android:strokeColor="{hexa(white if mono else ARC_COLOUR, 0.6 if mono else 1)}"'
        f' android:strokeWidth="{ARC_WIDTH}" android:strokeLineCap="round" />\n'
    )
    body.append(
        f'    <path android:pathData="{tick_path()}" android:strokeColor="{hexa(white if mono else SAGE)}"'
        f' android:strokeWidth="{TICK[2]}" android:strokeLineCap="round" />\n'
    )
    for x, y, r, colour, alpha in trail():
        body.append(f'    <path android:pathData="{circle(x, y, r)}" android:fillColor="{hexa(white, alpha) if mono else hexa(colour)}" />\n')
    x, y = on_arc(0)
    if not mono:
        body.append(
            f'    <path android:pathData="{circle(x, y, BLOOM)}">\n'
            '        <aapt:attr name="android:fillColor">\n'
            f'            <gradient android:type="radial" android:centerX="{x:.2f}" android:centerY="{y:.2f}" android:gradientRadius="{BLOOM}">\n'
            f'                <item android:offset="0" android:color="{hexa(HALO, 0.42)}" />\n'
            f'                <item android:offset="0.4" android:color="{hexa(HALO, 0.2)}" />\n'
            f'                <item android:offset="1" android:color="{hexa(HALO, 0)}" />\n'
            "            </gradient>\n"
            "        </aapt:attr>\n"
            "    </path>\n"
        )
    body.append(f'    <path android:pathData="{circle(x, y, ARRIVAL)}" android:fillColor="{hexa(white if mono else HALO)}" />\n')
    return "".join(body)


# In mipmap-anydpi-v26 even though minSdk is 26: <monochrome> is an API 33 tag, and without an
# explicit -v26 aapt would version the file to v33, leaving Android 8–12 with no icon at all.
ADAPTIVE = (
    '<?xml version="1.0" encoding="utf-8"?>\n'
    '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
    '    <background android:drawable="@drawable/ic_launcher_background" />\n'
    '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
    '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n'
    "</adaptive-icon>\n"
)


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(os.path.relpath(path, ROOT))

# endregion

# region Store icon

def render(size=512):
    """The visible middle 72 units, drawn at [size] px with 4× supersampling."""
    ss = size * 4
    u = ss / 72
    off = 18.0

    def p(x, y):
        return (x - off) * u, (y - off) * u

    # Background: the same radial lift as the vector, computed per pixel on a small grid.
    small = Image.new("RGB", (144, 144))
    px = small.load()
    for j in range(144):
        for i in range(144):
            x, y = off + (i + 0.5) / 2, off + (j + 0.5) / 2
            d = min(1.0, math.hypot(x - LIFT_CENTER[0], y - LIFT_CENTER[1]) / LIFT_RADIUS)
            px[i, j] = lerp(LIFT_COLOUR, BG, smooth(d))
    img = small.resize((ss, ss), Image.BICUBIC)
    d = ImageDraw.Draw(img)

    def stroke(points, width, colour):
        w = width * u
        d.line(points, fill=colour, width=round(w))
        for x, y in (points[0], points[-1]):
            d.ellipse([x - w / 2, y - w / 2, x + w / 2, y + w / 2], fill=colour)

    cx0, cy0 = p(CX, CY)
    w = ARC_WIDTH * u
    box = [cx0 - R * u - w / 2, cy0 - R * u - w / 2, cx0 + R * u + w / 2, cy0 + R * u + w / 2]
    d.arc(box, 270 - SPAN, 270 + SPAN, fill=ARC_COLOUR, width=round(w))
    for end in (-SPAN, SPAN):
        ex, ey = p(*on_arc(end))
        d.ellipse([ex - w / 2, ey - w / 2, ex + w / 2, ey + w / 2], fill=ARC_COLOUR)
    stroke([p(*on_arc(0, TICK[0])), p(*on_arc(0, TICK[1]))], TICK[2], SAGE)
    for x, y, r, colour, _ in trail():
        cx, cy = p(x, y)
        d.ellipse([cx - r * u, cy - r * u, cx + r * u, cy + r * u], fill=colour)
    # The bloom, as the vector's radial gradient: 0.42 at centre, 0.2 at 40%, gone at the edge.
    cx, cy = p(*on_arc(0))
    bloom = Image.new("L", (ss, ss), 0)
    bp = bloom.load()
    rad = BLOOM * u
    for j in range(max(0, int(cy - rad)), min(ss, int(cy + rad) + 1)):
        for i in range(max(0, int(cx - rad)), min(ss, int(cx + rad) + 1)):
            t = math.hypot(i - cx, j - cy) / rad
            if t < 1:
                a = 0.42 + (0.2 - 0.42) * t / 0.4 if t < 0.4 else 0.2 * (1 - (t - 0.4) / 0.6)
                bp[i, j] = round(a * 255)
    img = Image.composite(Image.new("RGB", (ss, ss), HALO), img, bloom)
    d = ImageDraw.Draw(img)
    r = ARRIVAL * u
    d.ellipse([cx - r, cy - r, cx + r, cy + r], fill=HALO)
    return img.resize((size, size), Image.LANCZOS)

# endregion


if __name__ == "__main__":
    write(os.path.join(RES, "drawable", "ic_launcher_background.xml"), vector(background_body()))
    write(os.path.join(RES, "drawable", "ic_launcher_foreground.xml"), vector(foreground_body()))
    write(os.path.join(RES, "drawable", "ic_launcher_monochrome.xml"), vector(foreground_body(mono=True)))
    write(os.path.join(RES, "drawable", "tuner_mark.xml"),
          vector(background_body() + foreground_body(), size=72, viewport=72, offset=18.0))
    write(os.path.join(RES, "mipmap-anydpi-v26", "ic_launcher.xml"), ADAPTIVE)
    write(os.path.join(RES, "mipmap-anydpi-v26", "ic_launcher_round.xml"), ADAPTIVE)
    render().save(STORE_ICON, optimize=True)
    print(os.path.relpath(STORE_ICON, ROOT))
